<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Musoq.Converter" Version="$(MusoqConverterVersion)"/>
        <PackageReference Include="Musoq.Evaluator" Version="$(MusoqEvaluatorVersion)"/>
        <PackageReference Include="Musoq.Schema" Version="$(MusoqSchemaVersion)"/>
    </ItemGroup>

</Project>
