<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Musoq.Converter" Version="17.0.0-alpha.7"/>
        <PackageReference Include="Musoq.Evaluator" Version="17.0.1-alpha.2"/>
        <PackageReference Include="Musoq.Schema" Version="17.0.0-alpha.7"/>
    </ItemGroup>

</Project>
